Api
szpp-dev-team/cvpn pull request #17
Opened 2021-03-18 14:57 UTC by earlgray283

2021-03-18 15:06 UTC, earlgray283 reviewed
レビューしました
あと、これからは push する前に必ず format をかけてください。

2021-03-18 15:06 UTC, earlgray283 commented on api/list.go
> +	lines := strings.Split(selection.Text(), ";\n")
列を揃えた方が見やすいね

2021-03-18 15:06 UTC, earlgray283 commented on api/list.go
> +		if first {
`first` って何？

2021-03-18 15:06 UTC, earlgray283 commented on api/list.go
> +		if len(tokens) == 3 {
`len(tokens) == 3` だったら dir, そうじゃなかったら file って感じかな？
そこらへんぱっと見じゃわかりづらいから、コメントしてもらえると嬉しい

2021-03-18 15:06 UTC, earlgray283 commented on api/list.go
> +			Size_value, _ := strconv.ParseFloat(Size_item[0], 64)
エラーハンドリング！

2021-03-18 15:06 UTC, earlgray283 commented on api/list.go
> +	var urls []SegmentInfo
普通に `segmentInfos` の方がわかりやすいかも

2021-03-21 01:49 UTC, nightshrine commented on api/list.go
> +		if first {
何故か最初の行だけ挙動がおかしいのでその修正。具体的に言うと最初の行だけ他の行と比べて一文字分後ろにずれてしまう…

2021-03-21 01:50 UTC, nightshrine commented on api/list.go
> +			Size_value, _ := strconv.ParseFloat(Size_item[0], 64)
どうやるかよくわからないので助けてください…！！

2021-03-21 01:56 UTC, nightshrine commented on api/list.go
> +	var urls []SegmentInfo
SegmentInfoは構造体の名前だからあまり変えたらまずいと思ってた…

2021-03-21 02:22 UTC, earlgray283 commented on api/list.go
> +		if first {
うーん、セパレータがおかしいのかな
ちょっとみておくね

2021-03-21 02:23 UTC, earlgray283 commented on api/list.go
> +	var urls []SegmentInfo
基本的には構造体の変数は構造体の型の名前の camelCase にすればいいよ

2021-03-21 02:24 UTC, earlgray283 commented on api/list.go
> +	var urls []SegmentInfo
基本的には構造体の変数は lowerCamelCase にすればいいよ

2021-03-22 12:41 UTC, arumakan1727 requested changes

2021-03-22 12:41 UTC, arumakan1727 commented on api/list.go
> +	_, err = findSegmentLines(doc)
`_, err = ...` ではなく `segmentInfos, err  = ...` かな？
`_` だと `[]SegmentInfo` の戻り値を捨てることになる & この関数先頭で宣言された `var segmentInfos` が未代入のまま return されている

2021-03-22 12:41 UTC, arumakan1727 commented on api/list.go
> +	)
引数  `path` が未使用になってるにゃん
http.NewRequest() 内の URLの末尾に `"https:// ...... dir=" + path` みたいにくっつけるのを忘れている？
('`/`' を '`\`' に変換したり特殊文字をエスケープしたりが必要かも (詳しく調べてない))

2021-03-22 12:41 UTC, arumakan1727 commented on api/list.go
> +	`)
CSSセレクタはこんなに冗長にしなくても 
```go
doc.Find("table#table_wfb_5 > tbody > script")
```

で十分だと思うにゃん
(知っているかもしれないけど、CSSセレクタの`#` は HTML の `id` 属性を指定するもので、`id` はHTMLページ内で一意に定まる識別子。 なので `table#table_wfb_5` で一意に定まる)

2021-03-22 12:41 UTC, arumakan1727 commented on api/list.go
> +	`)
ブラウザの開発者ツールの JSコンソールで、`document.querySelector("#table_wfb_5>tbody>script")` を実行して実際にこの CSS セレクタで <script> を取得できることを確認しました

2021-03-22 12:41 UTC, arumakan1727 commented on api/list.go
> +		if first {
ブラウザの開発者ツールの JSコンソールで、`document.querySelector("#table_wfb_5>tbody>script").text` をする (もしくは `....  ().text[0]`) と分かるけど、
文字列の先頭に改行文字が入ってるのが原因だと思うにゃん！！

だから最初の行だけ1文字文後ろにずれる

---

現状の `first` で分岐する方法で対処してもいいけど、
プログラムの見通しが悪くなるのと `first` という変化する状態変数を持つのとで直感的に嫌な気持ちになる()

そこで代替の解決策として、
```go
lines := strings.Split(selection.Text(), ";\n")
```
を修正して、最初の1文字をスキップしたスライスを渡すようにすれば良いんじゃないかな？↓
```go
lines := strings.Split(selection.Text()[1:], ";\n")
```
そうすれば `first` で条件分岐する必要がなくなると思う

2021-03-22 12:41 UTC, arumakan1727 commented on api/list.go
> +			Size_value, _ := strconv.ParseFloat(Size_item[0], 64)
これは僕がヘルプするべきということか？ 
浮動小数点数へのパースに失敗したら、関数呼び出し元にエラー返してあげればいいと思うにゃん
```go
Size_value, err := strconv.ParseFloat(............)
if err != nil {
    return nil, err
}
```

すでにDMで解決済みとかだったらごめん

2021-03-22 12:41 UTC, arumakan1727 commented on api/list.go
> +			Size_value, _ := strconv.ParseFloat(Size_item[0], 64)
ところで `Size_value` と `Size_unit` は public でもないのに変数名の先頭が大文字なのが気になったりならなかったりする

2021-03-22 15:02 UTC, nightshrine commented on api/list.go
> +	_, err = findSegmentLines(doc)
そこは僕の担当じゃないみたい…（）　でも参考にします！！！！！

2021-03-22 15:06 UTC, nightshrine commented on api/list.go
> +	)
多分今の段階では「report」の部分だけ出力できればいいってとわくんが言ってくれて、俺はそれに励んだ感じ。ただ今後はpathを指定して出せるようにしたいので今後の課題です。
あとここで言うのもあれかもだけど、こんなに一生懸命レビューしてくれてありがとうございます！！！！！！！！

2021-03-22 15:09 UTC, nightshrine commented on api/list.go
> +	`)
まじ？？？？　すげぇ…

2021-03-22 15:26 UTC, earlgray283 reviewed
気になった点
+ snake_case が多いから camelCase にしてほしい(変数名ではなく変数の形式)

2021-03-22 15:26 UTC, earlgray283 commented on api/list.go
> +		if len(tokens) == 3 { //ファイルの場合は要素数が3
ディレクトリじゃない？

2021-03-22 15:26 UTC, earlgray283 commented on api/list.go
> +		var tokens_seg SegmentInfo
camelCase

2021-03-22 15:26 UTC, earlgray283 commented on api/list.go
> +				Unit:      "",
golang は初期化されてなかったらゼロ値で初期化されるから `Unit: "",` でわざわざやる必要はないかな

2021-03-22 15:26 UTC, earlgray283 commented on api/list.go
> +				IsDir:     false,
ここも、bool は `false` で初期化されるからいらない

2021-03-22 15:26 UTC, earlgray283 commented on api/list.go
> +	var lowerCamelCase []SegmentInfo
これはなに？

2021-03-22 15:26 UTC, earlgray283 commented on api/list.go
> +	var lowerCamelCase []SegmentInfo
lowerCamelCase という変数名にしろってことではなく、`SegmentInfo` を lowerCamelCase にしたもの(つまり `segmentInfo` にすれば良いと伝えたかった

2021-03-22 15:26 UTC, earlgray283 commented on api/list.go
> +	var lowerCamelCase []SegmentInfo
さらに、`[]SegmentInfo` とスライスであるから、複数形の `segmentInfos` にすればなおよかった

2021-03-23 00:37 UTC, nightshrine commented on api/list.go
> +				Unit:      "",
nit: "",　て初期化しないと Unit: ,　だとエラーが出ちゃう…代替案を教えてほしい！！！

2021-03-23 00:57 UTC, earlgray283 commented on api/list.go
> +	`)
しりませんでした・・・・

2021-03-24 01:42 UTC, earlgray283 reviewed
あとちょっと、頑張って

2021-03-24 01:42 UTC, earlgray283 commented on api/list.go
> +	_, err = findSegmentLines(doc)
ないしゅらさんの担当ですね... ()
ここで戻り値を無視してるからテストで空のスライスしか表示されないのです(答え)

2021-03-24 01:42 UTC, earlgray283 commented on api/list.go
> +			var Size_unit string
ここ snake_case になってるよー

2021-03-24 01:42 UTC, earlgray283 commented on api/list.go
> +			var Size_unit string
あと、public ではないから `SizeUnit` ではなく `sizeUnit`

2021-03-24 01:43 UTC, earlgray283 commented
コンフリクトがえぐいことになってるな・・

2021-03-24 04:21 UTC, merged