Feature/#19 find
szpp-dev-team/cvpn pull request #34
Opened 2021-04-04 09:23 UTC by earlgray283

`find` サブコマンドを実装。

2021-04-05 12:12 UTC, arumakan1727 requested changes
ロジックの方はOKだと思います！！！！！
細かい指摘ばっかりになってしまって申し訳ない... 😣

2021-04-05 12:12 UTC, arumakan1727 commented on README.md
> +$ cvpn find {path} -v {volume} -name {name_pattern} -path {path_pattern}
- `$ cvpn find` の直後の `{path}` はフラグの `-path` と混同しやすそうかも...？
    `{path}` ではなく `{starting-directory}` とかにすると良さそう
    ※ Linux の `find` コマンドは `{starting-point}` だった

- `-name`, `-path` それぞれハイフンがもう一本必要だと思う

2021-04-05 12:12 UTC, arumakan1727 commented on README.md
> +$ cvpn find /cs200xx -v fs/2020 -name hogehoge
ここも、`-name` ではなくて `--name` だと思う！

2021-04-05 12:12 UTC, arumakan1727 commented on README.md
> +$ cvpn find {path} -v {volume} -name {name_pattern} -path {path_pattern}
あと、`--recursive` も載せたほうが良さそう

2021-04-05 12:12 UTC, arumakan1727 commented on README.md
>  ### Development
ここもハイフンは2本><

あと `-r, --recursive` の説明 :bow:

2021-04-05 12:12 UTC, arumakan1727 commented on pkg/subcmd/find.go
> +		Short: "find files or directories which matched pattern",
`which mathced ...` だけど、過去形ではなく現在形で `which matches ...` のほうが自然な気がする><

2021-04-05 12:12 UTC, arumakan1727 commented on pkg/subcmd/find.go
> +				return errors.New("path was not set")
*path* はオプションの `--path` と混同しやすそうだから、こんな感じに直すと良さそう
```suggestion
				return errors.New("{starting-directory} was not set")
```

2021-04-05 12:12 UTC, arumakan1727 commented on pkg/subcmd/find.go
> +}
~良いと思います！！！！！！！~

2021-04-05 12:12 UTC, arumakan1727 commented on README.md
>  ### Development
名前とパスが分かりにくい or 誤解する人が出てきそうだから、例があると分かりやすいかも

 ---

 **名前** は **パス** のうち末尾の部分を指します。
 例えば `/class/english/hoge.pdf` という文字列において、名前とパスはそれぞれ次のようになります。
 
 | 文字列 | `/class/english/hoge.pdf` |
 |----------|-------------------------------|
 | 名前 | `hoge.pdf` |
 | パス | `/class/english/hoge.pdf` |

2021-04-05 12:37 UTC, arumakan1727 commented on pkg/subcmd/find.go
> +}
「探索結果をスライスに貯める→探索が完了して初めて結果を表示する」よりも、
「結果が見つかるたびに表示」の方が嬉しい気がする

- `--recursive` を指定 & 探索領域が広い 場合など、探索に時間がかかる場合、その探索中に何も出力が無い。出力が無いまましばらく時間がかかると、本当に動いているのか不安(?) になってしまう

--- 

実装方法だけど，↓マッチしたやつが見つかった時にすべき処理を `matchHandler` みたいな関数で受け取るようにすると良さそう
(呼び出し側は引数に `func (path string) { fmt.Println(path) }` を渡す)

(Go の関数の書き方うろ覚えです、間違ってたらごめん)

```suggestion
func checkRegexp(pattern, s string) (bool, error) {
	return regexp.Match(pattern, []byte(s))
}

func searchMatches(client *api.Client, begin, volumeID string, matchHandler func(path string)void ) ([]string, error) {
	var stack, matchedPathes []string
	stack = append(stack, begin)
	for len(stack) > 0 {
		tail := len(stack) - 1
		segs, err := client.List(stack[tail], volumeID)
		if err != nil {
			return nil, err
		}
		stack = stack[:tail]

		for _, seg := range segs {
			ok1, err := checkRegexp(namePattern, seg.Name)
			if err != nil {
				return nil, err
			}
			ok2, err := checkRegexp(pathPattern, seg.Path)
			if err != nil {
				return nil, err
			}
			if ok1 && ok2 {
			        matchHandler(seg.Path)
			}
			if seg.IsDir && recursiveFlg {
				stack = append(stack, seg.Path)
			}
		}
	}

	return matchedPathes, nil
}
```

2021-04-05 13:27 UTC, earlgray283 commented on README.md
> +$ cvpn find {path} -v {volume} -name {name_pattern} -path {path_pattern}
うー、寝ぼけてたみたい・・ごめんなさい＞＜

2021-04-05 13:33 UTC, earlgray283 commented on README.md
>  ### Development
確かに、そこは盲点だった。
追加しておいたｂ

2021-04-05 13:34 UTC, earlgray283 commented on pkg/subcmd/find.go
> +		Short: "find files or directories which matched pattern",
英語なんもわからん

2021-04-05 13:43 UTC, earlgray283 commented on pkg/subcmd/find.go
> +}
`$ cvpn find / -r`
みたいな暴力をする人がいたら確かにその人困っちゃうね！！直しておいた。
あと、ラムダ式(?)にするデザインパターン素晴らしいです

2021-04-05 16:24 UTC, arumakan1727 approved these changes

2021-04-05 16:24 UTC, arumakan1727 commented on pkg/subcmd/find.go
> +	}
DFS(嘘) は気づかなかった><
そんなに気にならないからそのままでも良いと思う

それか、再帰関数で実装するか...？

2021-04-06 03:26 UTC, earlgray283 commented on pkg/subcmd/find.go
> +	}
再帰、スタックオーバーフローが怖い(ないとは思うけど)

あるまかんが認めているから、ヨシ！(merge)

2021-04-06 03:26 UTC, merged